module(..., package.seeall);


Magic = {
	{ Sequence = [[1]], NAME = [[命疗术]], MP = [[20]], POWER = [[100]], ATTACK = [[30]], SCRIPT = [[501]], ATTRIB = [[补血]], TITLE = [[博士]], NOTE = [[主将补血,L1]], ACTIVE = [[我方主将]],  },
	{ Sequence = [[2]], NAME = [[落月弓]], MP = [[18]], POWER = [[100]], ATTACK = [[15]], SCRIPT = [[502]], ATTRIB = [[主将2]], TITLE = [[议郎]], NOTE = [[主将射箭,L1]], ACTIVE = [[敌方主将]],  },
	{ Sequence = [[3]], NAME = [[地泉冲]], MP = [[19]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[504]], ATTRIB = [[全体]], TITLE = '', NOTE = [[水柱,L1]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[4]], NAME = [[火箭]], MP = [[20]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[503]], ATTRIB = [[全体,主将]], TITLE = [[黄门令]], NOTE = [[火箭支援,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[5]], NAME = [[伏兵组阵]], MP = [[21]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[509]], ATTRIB = [[补兵]], TITLE = [[长史]], NOTE = [[补兵,L2]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[6]], NAME = [[木轮攻]], MP = [[22]], POWER = [[100]], ATTACK = [[5]], SCRIPT = [[506]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[侧滚筒,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[7]], NAME = [[虎咆]], MP = [[21]], POWER = [[100]], ATTACK = [[7]], SCRIPT = [[508]], ATTRIB = [[四周]], TITLE = [[羽林监]], NOTE = [[主将四周乱爆,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[8]], NAME = [[火雷]], MP = [[22]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[505]], ATTRIB = [[全体]], TITLE = '', NOTE = [[炸弹地雷,L1]], ACTIVE = [[敌我全军]],  },
	{ Sequence = [[9]], NAME = [[雷击]], MP = [[22]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[510]], ATTRIB = [[全体]], TITLE = [[太使令]], NOTE = [[闪电,L1]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[10]], NAME = [[炎龙]], MP = [[23]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[512]], ATTRIB = [[全体,主将]], TITLE = [[郎中]], NOTE = [[火龙,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[11]], NAME = [[伏焰]], MP = [[23]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[507]], ATTRIB = [[全体]], TITLE = '', NOTE = [[放火,L1]], ACTIVE = [[敌我全军]],  },
	{ Sequence = [[12]], NAME = [[拒陆马]], MP = [[24]], POWER = [[100]], ATTACK = [[20]], SCRIPT = [[513]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[退兵阻碍,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[13]], NAME = [[御飞刀]], MP = [[25]], POWER = [[100]], ATTACK = [[20]], SCRIPT = [[514]], ATTRIB = [[主将2]], TITLE = [[太使大夫]], NOTE = [[飞刀,L2]], ACTIVE = [[敌方主将]],  },
	{ Sequence = [[14]], NAME = [[雷光波动]], MP = [[25]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[511]], ATTRIB = [[全体]], TITLE = '', NOTE = [[电力波及,L1]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[15]], NAME = [[火箭烈]], MP = [[26]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[515]], ATTRIB = [[全体,主将]], TITLE = [[御史中丞]], NOTE = [[火箭支援,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[16]], NAME = [[虎咆震]], MP = [[26]], POWER = [[100]], ATTACK = [[7]], SCRIPT = [[519]], ATTRIB = [[四周]], TITLE = [[中常侍]], NOTE = [[主将四周乱爆,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[17]], NAME = [[伏兵排阵]], MP = [[28]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[523]], ATTRIB = [[补兵]], TITLE = [[太傅]], NOTE = [[补兵,L3]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[18]], NAME = [[地泉裂劲]], MP = [[29]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[516]], ATTRIB = [[全体]], TITLE = '', NOTE = [[水柱,L2]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[19]], NAME = [[後伏连兵]], MP = [[30]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[524]], ATTRIB = [[补兵]], TITLE = '', NOTE = [[後伏兵,L1]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[20]], NAME = [[木轮强袭]], MP = [[31]], POWER = [[100]], ATTACK = [[5]], SCRIPT = [[518]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[侧滚筒,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[21]], NAME = [[炎龙无双]], MP = [[35]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[520]], ATTRIB = [[全体,主将]], TITLE = [[侍中]], NOTE = [[火龙,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[22]], NAME = [[雷光振杀]], MP = [[35]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[522]], ATTRIB = [[全体]], TITLE = '', NOTE = [[电力波及,L2]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[23]], NAME = [[虎咆阳炎]], MP = [[35]], POWER = [[100]], ATTACK = [[7]], SCRIPT = [[531]], ATTRIB = [[四周]], TITLE = [[大司农]], NOTE = [[主将四周乱爆,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[24]], NAME = [[火雷爆]], MP = [[36]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[517]], ATTRIB = [[全体]], TITLE = '', NOTE = [[炸弹地雷,L2]], ACTIVE = [[敌我全军]],  },
	{ Sequence = [[25]], NAME = [[黄龙天翔]], MP = [[38]], POWER = [[100]], ATTACK = [[12]], SCRIPT = [[526]], ATTRIB = [[全体,主将]], TITLE = [[司徒]], NOTE = [[召唤龙,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[26]], NAME = [[地泉鲸浪]], MP = [[38]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[532]], ATTRIB = [[全体]], TITLE = '', NOTE = [[水柱,L3]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[27]], NAME = [[绝命坝]], MP = [[38]], POWER = [[100]], ATTACK = [[20]], SCRIPT = [[527]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[退兵阻碍,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[28]], NAME = [[雷击闪]], MP = [[39]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[525]], ATTRIB = [[全体]], TITLE = [[尚书令]], NOTE = [[闪电,L2]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[29]], NAME = [[炎龙杀阵]], MP = [[40]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[528]], ATTRIB = [[全体,主将]], TITLE = [[太尉]], NOTE = [[火龙,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[30]], NAME = [[火箭天袭]], MP = [[40]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[534]], ATTRIB = [[全体,主将]], TITLE = [[大司马]], NOTE = [[火箭支援,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[31]], NAME = [[後伏兵阵]], MP = [[41]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[533]], ATTRIB = [[补兵]], TITLE = '', NOTE = [[後伏兵,L2]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[32]], NAME = [[火雷星雨]], MP = [[42]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[530]], ATTRIB = [[全体]], TITLE = '', NOTE = [[炸弹地雷,L3]], ACTIVE = [[敌我全军]],  },
	{ Sequence = [[33]], NAME = [[炎龙怒涛]], MP = [[43]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[536]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[火龙,L4]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[34]], NAME = [[赤焰洪流]], MP = [[41]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[521]], ATTRIB = [[全体]], TITLE = '', NOTE = [[放火,L2]], ACTIVE = [[敌我全军]],  },
	{ Sequence = [[35]], NAME = [[木轮涛击]], MP = [[44]], POWER = [[100]], ATTACK = [[5]], SCRIPT = [[535]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[侧滚筒,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[36]], NAME = [[赤焰火海]], MP = [[49]], POWER = [[100]], ATTACK = [[6]], SCRIPT = [[529]], ATTRIB = [[全体]], TITLE = '', NOTE = [[放火,L3]], ACTIVE = [[敌我全军]],  },
	{ Sequence = [[37]], NAME = [[後伏军阵]], MP = [[42]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[541]], ATTRIB = [[补兵]], TITLE = '', NOTE = [[後伏兵,L3]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[38]], NAME = [[大地狂啸]], MP = [[48]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[540]], ATTRIB = [[全体]], TITLE = '', NOTE = [[地震,L1]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[39]], NAME = [[雷光燋狱]], MP = [[43]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[538]], ATTRIB = [[全体]], TITLE = '', NOTE = [[电力波及,L3]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[40]], NAME = [[十面埋伏]], MP = [[23]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[539]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[退兵阻碍,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[41]], NAME = [[炎龙绝杀]], MP = [[49]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[542]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[火龙,L4]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[42]], NAME = [[五雷轰顶]], MP = [[45]], POWER = [[100]], ATTACK = [[40]], SCRIPT = [[537]], ATTRIB = [[主将2]], TITLE = [[司空]], NOTE = [[闪电,L3]], ACTIVE = [[敌方主将]],  },
	{ Sequence = [[43]], NAME = [[狂雷天牢]], MP = [[50]], POWER = [[100]], ATTACK = [[48]], SCRIPT = [[543]], ATTRIB = [[主将2]], TITLE = '', NOTE = [[雷球,L1]], ACTIVE = [[敌方主将]],  },
	{ Sequence = [[44]], NAME = [[天地无用]], MP = [[50]], POWER = [[100]], ATTACK = [[30]], SCRIPT = [[544]], ATTRIB = [[全体,主将]], TITLE = [[丞相]], NOTE = [[丞相组合计,L4]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[45]], NAME = [[飞矢]], MP = [[18]], POWER = [[100]], ATTACK = [[5]], SCRIPT = [[545]], ATTRIB = [[全体,主将]], TITLE = [[安国将军]], NOTE = [[弓箭支援,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[46]], NAME = [[连弩]], MP = [[20]], POWER = [[100]], ATTACK = [[20]], SCRIPT = [[546]], ATTRIB = [[中间,主将2]], TITLE = '', NOTE = [[连弩,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[47]], NAME = [[突石]], MP = [[20]], POWER = [[100]], ATTACK = [[11]], SCRIPT = [[548]], ATTRIB = [[全体,主将]], TITLE = [[司隶校尉]], NOTE = [[突石,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[48]], NAME = [[落石]], MP = [[18]], POWER = [[100]], ATTACK = [[9]], SCRIPT = [[547]], ATTRIB = [[全体,主将]], TITLE = [[军师将军]], NOTE = [[投石车投普通石头,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[49]], NAME = [[刀剑乱]], MP = [[18]], POWER = [[100]], ATTACK = [[7]], SCRIPT = [[553]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[乱刀剑,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[50]], NAME = [[半月斩]], MP = [[22]], POWER = [[100]], ATTACK = [[12]], SCRIPT = [[550]], ATTRIB = [[中间,主将2]], TITLE = [[横江将军]], NOTE = [[WAVE,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[51]], NAME = [[旋龙]], MP = [[22]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[554]], ATTRIB = [[全体]], TITLE = [[牙门将军]], NOTE = [[龙卷风,L1]], ACTIVE = [[敌我士兵]],  },
	{ Sequence = [[52]], NAME = [[落日弓]], MP = [[22]], POWER = [[100]], ATTACK = [[25]], SCRIPT = [[552]], ATTRIB = [[主将2]], TITLE = [[偏将军]], NOTE = [[主将射箭,L1]], ACTIVE = [[敌方主将]],  },
	{ Sequence = [[53]], NAME = [[八面火]], MP = [[23]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[556]], ATTRIB = [[四周]], TITLE = [[骁骑校尉]], NOTE = [[主将八方爆裂,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[54]], NAME = [[旋灯火]], MP = [[23]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[549]], ATTRIB = [[四周]], TITLE = '', NOTE = [[火圈,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[55]], NAME = [[突石剑]], MP = [[23]], POWER = [[100]], ATTACK = [[11]], SCRIPT = [[575]], ATTRIB = [[全体,主将]], TITLE = [[伏波将军]], NOTE = [[突石,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[56]], NAME = [[太极门]], MP = [[23]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[557]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[爆炸（太极）,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[57]], NAME = [[伏兵班阵]], MP = [[21]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[565]], ATTRIB = [[补兵]], TITLE = [[虎威将军]], NOTE = [[补兵,L2]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[58]], NAME = [[八门金锁]], MP = [[20]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[585]], ATTRIB = [[全体]], TITLE = [[征虏将军]], NOTE = [[敌兵暂停,L3]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[59]], NAME = [[鬼戟]], MP = [[24]], POWER = [[100]], ATTACK = [[14]], SCRIPT = [[558]], ATTRIB = [[中间,主将2]], TITLE = [[裨将军]], NOTE = [[主将射戟,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[60]], NAME = [[回天术]], MP = [[26]], POWER = [[100]], ATTACK = [[35]], SCRIPT = [[563]], ATTRIB = [[补血]], TITLE = [[辅国将军]], NOTE = [[主将补血,L2]], ACTIVE = [[我方主将]],  },
	{ Sequence = [[61]], NAME = [[地茅刺]], MP = [[26]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[562]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[地刺茅,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[62]], NAME = [[连弩激射]], MP = [[26]], POWER = [[100]], ATTACK = [[32]], SCRIPT = [[564]], ATTRIB = [[中间,主将2]], TITLE = '', NOTE = [[连弩,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[63]], NAME = [[冰柱刺]], MP = [[26]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[551]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[冰柱刺,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[64]], NAME = [[突剑四方]], MP = [[27]], POWER = [[100]], ATTACK = [[12]], SCRIPT = [[593]], ATTRIB = [[全体,主将]], TITLE = [[安南将军]], NOTE = [[突石,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[65]], NAME = [[冲车]], MP = [[27]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[567]], ATTRIB = [[两侧]], TITLE = [[越骑校尉]], NOTE = [[冲车,L1]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[66]], NAME = [[神剑]], MP = [[28]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[561]], ATTRIB = [[全体,主将]], TITLE = [[典军校尉]], NOTE = [[飞剑,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[67]], NAME = [[八面火转]], MP = [[28]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[568]], ATTRIB = [[四周]], TITLE = [[昭文将军]], NOTE = [[主将八方爆裂,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[68]], NAME = [[突袭石]], MP = [[28]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[555]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[侧滚石,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[69]], NAME = [[龙炮]], MP = [[29]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[560]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[尾纹爆炸,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[70]], NAME = [[火牛阵]], MP = [[30]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[559]], ATTRIB = [[中间,主将]], TITLE = '', NOTE = [[火牛阵,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[71]], NAME = [[生死门]], MP = [[31]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[566]], ATTRIB = [[全体]], TITLE = '', NOTE = [[黑洞,L1]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[72]], NAME = [[乱飞矢]], MP = [[32]], POWER = [[100]], ATTACK = [[5]], SCRIPT = [[572]], ATTRIB = [[全体,主将]], TITLE = [[鹰扬将军]], NOTE = [[弓箭支援,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[73]], NAME = [[地茅乱刺]], MP = [[33]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[582]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[地刺茅,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[74]], NAME = [[龙炮激射]], MP = [[34]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[578]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[尾纹爆炸,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[75]], NAME = [[旋龙合璧]], MP = [[34]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[580]], ATTRIB = [[全体]], TITLE = [[扬武将军]], NOTE = [[龙卷风,L2]], ACTIVE = [[敌我士兵]],  },
	{ Sequence = [[76]], NAME = [[冰柱群锋]], MP = [[34]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[579]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[冰柱刺,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[77]], NAME = [[烈火旋灯]], MP = [[35]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[569]], ATTRIB = [[四周]], TITLE = '', NOTE = [[火圈,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[78]], NAME = [[太极华阵]], MP = [[36]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[573]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[爆炸（太极）,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[79]], NAME = [[滚石遽压]], MP = [[36]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[576]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[侧滚石,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[80]], NAME = [[八卦奇阵]], MP = [[37]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[594]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[爆炸（八卦）,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[81]], NAME = [[伏兵连阵]], MP = [[37]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[584]], ATTRIB = [[补兵]], TITLE = [[卫将军]], NOTE = [[补兵,L3]], ACTIVE = [[我方士兵]],  },
	{ Sequence = [[82]], NAME = [[驷冲车]], MP = [[38]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[586]], ATTRIB = [[两侧]], TITLE = [[折冲将军]], NOTE = [[冲车,L2]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[83]], NAME = [[三日月斩]], MP = [[38]], POWER = [[100]], ATTACK = [[12]], SCRIPT = [[577]], ATTRIB = [[中间,主将2]], TITLE = [[荡寇将军]], NOTE = [[WAVE,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[84]], NAME = [[神剑闪]], MP = [[38]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[570]], ATTRIB = [[全体,主将]], TITLE = [[讨逆将军]], NOTE = [[飞剑,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[85]], NAME = [[连弩狂涛]], MP = [[38]], POWER = [[100]], ATTACK = [[44]], SCRIPT = [[587]], ATTRIB = [[中间,主将2]], TITLE = '', NOTE = [[连弩,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[86]], NAME = [[乱刀狂舞]], MP = [[39]], POWER = [[100]], ATTACK = [[7]], SCRIPT = [[581]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[乱刀剑,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[87]], NAME = [[飞矢烈震]], MP = [[39]], POWER = [[100]], ATTACK = [[5]], SCRIPT = [[590]], ATTRIB = [[全体,主将]], TITLE = [[镇西将军]], NOTE = [[弓箭支援,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[88]], NAME = [[三圣华斩]], MP = [[40]], POWER = [[100]], ATTACK = [[25]], SCRIPT = [[592]], ATTRIB = [[全体,主将2]], TITLE = '', NOTE = [[会集中攻击武将的半月斩,L4]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[89]], NAME = [[神火旋张]], MP = [[40]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[571]], ATTRIB = [[四周]], TITLE = '', NOTE = [[火圈,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[90]], NAME = [[龙炮灭杀]], MP = [[40]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[599]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[尾纹爆炸,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[91]], NAME = [[炬石轰]], MP = [[41]], POWER = [[100]], ATTACK = [[11]], SCRIPT = [[583]], ATTRIB = [[全体,主将]], TITLE = [[镇军将军]], NOTE = [[投石车投火石,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[92]], NAME = [[火牛群舞]], MP = [[42]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[574]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[火牛阵,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[93]], NAME = [[茅刺遍地]], MP = [[42]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[603]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[地刺茅,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[94]], NAME = [[滚石怒冲]], MP = [[43]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[597]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[侧滚石,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[95]], NAME = [[剑轮舞]], MP = [[44]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[606]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[剑轮舞,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[96]], NAME = [[分身斩]], MP = [[44]], POWER = [[100]], ATTACK = [[35]], SCRIPT = [[598]], ATTRIB = [[中间,主将2]], TITLE = [[龙骧将军]], NOTE = [[分身斩,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[97]], NAME = [[冰岚刃舞]], MP = [[44]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[601]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[冰柱刺,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[98]], NAME = [[神剑闪华]], MP = [[45]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[595]], ATTRIB = [[全体,主将]], TITLE = [[平北将军]], NOTE = [[飞剑,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[99]], NAME = [[炎墙]], MP = [[45]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[600]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[火墙（或龙卷风）,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[100]], NAME = [[旋龙天舞]], MP = [[46]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[588]], ATTRIB = [[全体]], TITLE = [[征东将军]], NOTE = [[龙卷风,L3]], ACTIVE = [[敌我士兵]],  },
	{ Sequence = [[101]], NAME = [[地狱之门]], MP = [[46]], POWER = [[100]], ATTACK = [[0]], SCRIPT = [[589]], ATTRIB = [[全体]], TITLE = '', NOTE = [[黑洞,L2]], ACTIVE = [[敌方士兵]],  },
	{ Sequence = [[102]], NAME = [[集火柱]], MP = [[47]], POWER = [[100]], ATTACK = [[9]], SCRIPT = [[607]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[集火柱,L1]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[103]], NAME = [[神火怒张]], MP = [[47]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[591]], ATTRIB = [[四周]], TITLE = '', NOTE = [[火圈,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[104]], NAME = [[神鬼乱舞]], MP = [[47]], POWER = [[100]], ATTACK = [[60]], SCRIPT = [[605]], ATTRIB = [[主将2]], TITLE = [[车骑将军]], NOTE = [[主将乱砍,L3]], ACTIVE = [[敌方主将]],  },
	{ Sequence = [[105]], NAME = [[炬石炼狱]], MP = [[48]], POWER = [[100]], ATTACK = [[11]], SCRIPT = [[604]], ATTRIB = [[全体,主将]], TITLE = [[前将军]], NOTE = [[投石车投火石,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[106]], NAME = [[炎墙烈烧]], MP = [[48]], POWER = [[100]], ATTACK = [[8]], SCRIPT = [[608]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[火墙（或龙卷风）,L2]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[107]], NAME = [[日月轮斩]], MP = [[49]], POWER = [[100]], ATTACK = [[12]], SCRIPT = [[602]], ATTRIB = [[全体,主将2]], TITLE = [[骠骑将军]], NOTE = [[WAVE,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[108]], NAME = [[火牛烈崩]], MP = [[49]], POWER = [[100]], ATTACK = [[10]], SCRIPT = [[596]], ATTRIB = [[全体,主将]], TITLE = '', NOTE = [[火牛阵,L3]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[109]], NAME = [[五岳华斩]], MP = [[49]], POWER = [[100]], ATTACK = [[45]], SCRIPT = [[609]], ATTRIB = [[全体,主将2]], TITLE = '', NOTE = [[会集中攻击武将的半月斩,L5]], ACTIVE = [[敌方全军]],  },
	{ Sequence = [[110]], NAME = [[鬼哭神号]], MP = [[50]], POWER = [[100]], ATTACK = [[50]], SCRIPT = [[610]], ATTRIB = [[全体,主将]], TITLE = [[大将军]], NOTE = [[将军组合计,L4]], ACTIVE = [[敌方全军]],  },
}

Wise = {
	{ Sequence = [[1]], Execute = [[4]], WiseLevel = [[1]], NAME = [[鼓舞士气]], ATTRIB = [[0]], Level = [[120]], ACTIVE = [[1]],  },
	{ Sequence = [[2]], Execute = [[1]], WiseLevel = [[1]], NAME = [[降敌士气]], ATTRIB = [[0]], Level = [[120]], ACTIVE = [[4]],  },
	{ Sequence = [[3]], Execute = [[34]], WiseLevel = [[0]], NAME = [[後选出阵]], ATTRIB = [[1]], Level = [[130]], ACTIVE = [[8]],  },
	{ Sequence = [[4]], Execute = [[9]], WiseLevel = [[1]], NAME = [[扰乱敌将]], ATTRIB = [[0]], Level = [[140]], ACTIVE = [[8]],  },
	{ Sequence = [[5]], Execute = [[12]], WiseLevel = [[1]], NAME = [[减少疲劳]], ATTRIB = [[0]], Level = [[140]], ACTIVE = [[2]],  },
	{ Sequence = [[6]], Execute = [[30]], WiseLevel = [[1]], NAME = [[离间计]], ATTRIB = [[0]], Level = [[160]], ACTIVE = [[8]],  },
	{ Sequence = [[7]], Execute = [[65]], WiseLevel = [[1]], NAME = [[减缓集气]], ATTRIB = [[0]], Level = [[160]], ACTIVE = [[8]],  },
	{ Sequence = [[8]], Execute = [[61]], WiseLevel = [[1]], NAME = [[保留气力]], ATTRIB = [[0]], Level = [[160]], ACTIVE = [[2]],  },
	{ Sequence = [[9]], Execute = [[50]], WiseLevel = [[1]], NAME = [[快速集气]], ATTRIB = [[0]], Level = [[160]], ACTIVE = [[2]],  },
	{ Sequence = [[10]], Execute = [[45]], WiseLevel = [[0]], NAME = [[诈败]], ATTRIB = [[0]], Level = [[170]], ACTIVE = [[2]],  },
	{ Sequence = [[11]], Execute = [[35]], WiseLevel = [[1]], NAME = [[恢复体力]], ATTRIB = [[0]], Level = [[170]], ACTIVE = [[2]],  },
	{ Sequence = [[12]], Execute = [[38]], WiseLevel = [[1]], NAME = [[恢复技力]], ATTRIB = [[0]], Level = [[180]], ACTIVE = [[2]],  },
	{ Sequence = [[13]], Execute = [[18]], WiseLevel = [[1]], NAME = [[增加技力]], ATTRIB = [[0]], Level = [[180]], ACTIVE = [[2]],  },
	{ Sequence = [[14]], Execute = [[15]], WiseLevel = [[1]], NAME = [[增加体力]], ATTRIB = [[0]], Level = [[180]], ACTIVE = [[2]],  },
	{ Sequence = [[15]], Execute = [[27]], WiseLevel = [[1]], NAME = [[混乱敌军]], ATTRIB = [[0]], Level = [[190]], ACTIVE = [[4]],  },
	{ Sequence = [[16]], Execute = [[24]], WiseLevel = [[1]], NAME = [[强化士兵]], ATTRIB = [[0]], Level = [[190]], ACTIVE = [[4]],  },
	{ Sequence = [[17]], Execute = [[21]], WiseLevel = [[1]], NAME = [[增强攻击]], ATTRIB = [[0]], Level = [[190]], ACTIVE = [[1]],  },
	{ Sequence = [[18]], Execute = [[5]], WiseLevel = [[2]], NAME = [[鼓舞士气]], ATTRIB = [[0]], Level = [[200]], ACTIVE = [[1]],  },
	{ Sequence = [[19]], Execute = [[2]], WiseLevel = [[2]], NAME = [[降敌士气]], ATTRIB = [[0]], Level = [[200]], ACTIVE = [[4]],  },
	{ Sequence = [[20]], Execute = [[58]], WiseLevel = [[1]], NAME = [[喝阻敌军]], ATTRIB = [[0]], Level = [[210]], ACTIVE = [[4]],  },
	{ Sequence = [[21]], Execute = [[53]], WiseLevel = [[1]], NAME = [[增加经验]], ATTRIB = [[0]], Level = [[220]], ACTIVE = [[2]],  },
	{ Sequence = [[22]], Execute = [[41]], WiseLevel = [[1]], NAME = [[强化武将]], ATTRIB = [[0]], Level = [[230]], ACTIVE = [[2]],  },
	{ Sequence = [[23]], Execute = [[49]], WiseLevel = [[0]], NAME = [[逼近敌军]], ATTRIB = [[3]], Level = [[230]], ACTIVE = [[1]],  },
	{ Sequence = [[24]], Execute = [[57]], WiseLevel = [[0]], NAME = [[化解计策]], ATTRIB = [[2]], Level = [[230]], ACTIVE = [[2]],  },
	{ Sequence = [[25]], Execute = [[10]], WiseLevel = [[2]], NAME = [[扰乱敌将]], ATTRIB = [[0]], Level = [[240]], ACTIVE = [[8]],  },
	{ Sequence = [[26]], Execute = [[47]], WiseLevel = [[0]], NAME = [[包围敌军]], ATTRIB = [[3]], Level = [[240]], ACTIVE = [[1]],  },
	{ Sequence = [[27]], Execute = [[13]], WiseLevel = [[2]], NAME = [[减少疲劳]], ATTRIB = [[0]], Level = [[240]], ACTIVE = [[2]],  },
	{ Sequence = [[28]], Execute = [[7]], WiseLevel = [[0]], NAME = [[乱阵]], ATTRIB = [[0]], Level = [[250]], ACTIVE = [[4]],  },
	{ Sequence = [[29]], Execute = [[8]], WiseLevel = [[0]], NAME = [[太公阵]], ATTRIB = [[0]], Level = [[250]], ACTIVE = [[1]],  },
	{ Sequence = [[30]], Execute = [[48]], WiseLevel = [[0]], NAME = [[偷袭敌军]], ATTRIB = [[3]], Level = [[250]], ACTIVE = [[1]],  },
	{ Sequence = [[31]], Execute = [[46]], WiseLevel = [[0]], NAME = [[保护主将]], ATTRIB = [[0]], Level = [[250]], ACTIVE = [[1]],  },
	{ Sequence = [[32]], Execute = [[33]], WiseLevel = [[0]], NAME = [[劝降]], ATTRIB = [[1]], Level = [[260]], ACTIVE = [[8]],  },
	{ Sequence = [[33]], Execute = [[56]], WiseLevel = [[0]], NAME = [[金蝉脱壳]], ATTRIB = [[0]], Level = [[270]], ACTIVE = [[2]],  },
	{ Sequence = [[34]], Execute = [[31]], WiseLevel = [[2]], NAME = [[离间计]], ATTRIB = [[0]], Level = [[270]], ACTIVE = [[8]],  },
	{ Sequence = [[35]], Execute = [[66]], WiseLevel = [[2]], NAME = [[减缓集气]], ATTRIB = [[0]], Level = [[280]], ACTIVE = [[8]],  },
	{ Sequence = [[36]], Execute = [[62]], WiseLevel = [[2]], NAME = [[保留气力]], ATTRIB = [[0]], Level = [[280]], ACTIVE = [[2]],  },
	{ Sequence = [[37]], Execute = [[51]], WiseLevel = [[2]], NAME = [[快速集气]], ATTRIB = [[0]], Level = [[280]], ACTIVE = [[2]],  },
	{ Sequence = [[38]], Execute = [[6]], WiseLevel = [[3]], NAME = [[鼓舞士气]], ATTRIB = [[0]], Level = [[300]], ACTIVE = [[1]],  },
	{ Sequence = [[39]], Execute = [[3]], WiseLevel = [[3]], NAME = [[降敌士气]], ATTRIB = [[0]], Level = [[300]], ACTIVE = [[4]],  },
	{ Sequence = [[40]], Execute = [[36]], WiseLevel = [[2]], NAME = [[恢复体力]], ATTRIB = [[0]], Level = [[320]], ACTIVE = [[2]],  },
	{ Sequence = [[41]], Execute = [[39]], WiseLevel = [[2]], NAME = [[恢复技力]], ATTRIB = [[0]], Level = [[320]], ACTIVE = [[2]],  },
	{ Sequence = [[42]], Execute = [[19]], WiseLevel = [[2]], NAME = [[增加技力]], ATTRIB = [[0]], Level = [[340]], ACTIVE = [[2]],  },
	{ Sequence = [[43]], Execute = [[16]], WiseLevel = [[2]], NAME = [[增加体力]], ATTRIB = [[0]], Level = [[340]], ACTIVE = [[2]],  },
	{ Sequence = [[44]], Execute = [[28]], WiseLevel = [[2]], NAME = [[混乱敌军]], ATTRIB = [[0]], Level = [[350]], ACTIVE = [[4]],  },
	{ Sequence = [[45]], Execute = [[25]], WiseLevel = [[2]], NAME = [[强化士兵]], ATTRIB = [[0]], Level = [[360]], ACTIVE = [[4]],  },
	{ Sequence = [[46]], Execute = [[22]], WiseLevel = [[2]], NAME = [[增强攻击]], ATTRIB = [[0]], Level = [[360]], ACTIVE = [[1]],  },
	{ Sequence = [[47]], Execute = [[54]], WiseLevel = [[2]], NAME = [[增加经验]], ATTRIB = [[0]], Level = [[370]], ACTIVE = [[2]],  },
	{ Sequence = [[48]], Execute = [[59]], WiseLevel = [[2]], NAME = [[喝阻敌军]], ATTRIB = [[0]], Level = [[380]], ACTIVE = [[4]],  },
	{ Sequence = [[49]], Execute = [[42]], WiseLevel = [[2]], NAME = [[强化武将]], ATTRIB = [[0]], Level = [[390]], ACTIVE = [[2]],  },
	{ Sequence = [[50]], Execute = [[14]], WiseLevel = [[3]], NAME = [[减少疲劳]], ATTRIB = [[0]], Level = [[400]], ACTIVE = [[2]],  },
	{ Sequence = [[51]], Execute = [[11]], WiseLevel = [[3]], NAME = [[扰乱敌将]], ATTRIB = [[0]], Level = [[400]], ACTIVE = [[8]],  },
	{ Sequence = [[52]], Execute = [[52]], WiseLevel = [[3]], NAME = [[快速集气]], ATTRIB = [[0]], Level = [[410]], ACTIVE = [[2]],  },
	{ Sequence = [[53]], Execute = [[67]], WiseLevel = [[3]], NAME = [[减缓集气]], ATTRIB = [[0]], Level = [[410]], ACTIVE = [[8]],  },
	{ Sequence = [[54]], Execute = [[44]], WiseLevel = [[0]], NAME = [[十面埋伏]], ATTRIB = [[0]], Level = [[420]], ACTIVE = [[8]],  },
	{ Sequence = [[55]], Execute = [[32]], WiseLevel = [[3]], NAME = [[离间计]], ATTRIB = [[0]], Level = [[420]], ACTIVE = [[8]],  },
	{ Sequence = [[56]], Execute = [[63]], WiseLevel = [[3]], NAME = [[保留气力]], ATTRIB = [[0]], Level = [[420]], ACTIVE = [[2]],  },
	{ Sequence = [[57]], Execute = [[37]], WiseLevel = [[3]], NAME = [[恢复体力]], ATTRIB = [[0]], Level = [[430]], ACTIVE = [[2]],  },
	{ Sequence = [[58]], Execute = [[40]], WiseLevel = [[3]], NAME = [[恢复技力]], ATTRIB = [[0]], Level = [[430]], ACTIVE = [[2]],  },
	{ Sequence = [[59]], Execute = [[64]], WiseLevel = [[0]], NAME = [[封武将技]], ATTRIB = [[0]], Level = [[450]], ACTIVE = [[8]],  },
	{ Sequence = [[60]], Execute = [[20]], WiseLevel = [[3]], NAME = [[增加技力]], ATTRIB = [[0]], Level = [[450]], ACTIVE = [[2]],  },
	{ Sequence = [[61]], Execute = [[17]], WiseLevel = [[3]], NAME = [[增加体力]], ATTRIB = [[0]], Level = [[450]], ACTIVE = [[2]],  },
	{ Sequence = [[62]], Execute = [[29]], WiseLevel = [[3]], NAME = [[混乱敌军]], ATTRIB = [[0]], Level = [[460]], ACTIVE = [[4]],  },
	{ Sequence = [[63]], Execute = [[26]], WiseLevel = [[3]], NAME = [[强化士兵]], ATTRIB = [[0]], Level = [[460]], ACTIVE = [[4]],  },
	{ Sequence = [[64]], Execute = [[23]], WiseLevel = [[3]], NAME = [[增强攻击]], ATTRIB = [[0]], Level = [[460]], ACTIVE = [[1]],  },
	{ Sequence = [[65]], Execute = [[55]], WiseLevel = [[3]], NAME = [[增加经验]], ATTRIB = [[0]], Level = [[470]], ACTIVE = [[2]],  },
	{ Sequence = [[66]], Execute = [[60]], WiseLevel = [[3]], NAME = [[喝阻敌军]], ATTRIB = [[0]], Level = [[480]], ACTIVE = [[4]],  },
	{ Sequence = [[67]], Execute = [[43]], WiseLevel = [[3]], NAME = [[强化武将]], ATTRIB = [[0]], Level = [[490]], ACTIVE = [[2]],  },
}
