module(..., package.seeall);


System = {
	TotalObjectDefine = [[300]],
}

Define = {
	TYPE_BASE = [[1]],
	TYPE_TROOP = [[2]],
	TYPE_FORCE = [[3]],
	TYPE_MAJOR = [[4]],
	DefaultObjectProcess = [[1]],
	TroopObjectProcess = [[2]],
	ForceSoldierObjectProcess = [[3]],
	ForceMajorObjectProcess = [[4]],
	GeneralObjectProcess = [[5]],
	MagicWaveProcess = [[6]],
	MagicFireProcess = [[7]],
	MagicRainProcess = [[8]],
	MagicArrowProcess = [[9]],
	TroopFlagsProcess = [[10]],
	MagicObjectProcess = [[11]],
	ForceArrowObjectProcess = [[12]],
	ShadowObjectProcess = [[13]],
	MajorWeaponProcess = [[15]],
	ForceHorseProcess = [[16]],
	TroopShapeObjectProcess = [[17]],
	MajorHorseProcess = [[18]],
	WeatherObjectProcess = [[19]],
	AniObjectProcess = [[20]],
	MajorGeneralWeaponProcess = [[21]],
	OF_MAN = [[0x00000001]],
	OF_MISSILE = [[0x00000002]],
	OF_BACKGROUND = [[0x00000004]],
	OF_CAVALRY = [[0x00000008]],
	OF_BLOCKMAN = [[0x00000010]],
	OF_BLOCKMISSILE = [[0x00000020]],
	OF_BIGSHAPE = [[0x00000040]],
	OF_TRIGGERMAN = [[0x00000100]],
	OF_TRIGGERMISSILE = [[0x00000200]],
	OF_NOGRAVITY = [[0x00010000]],
	OF_NONSYNCHRONISM = [[0x00020000]],
	OF_MIXER = [[0x00040000]],
	OF_WHITELIGHT = [[0x00080000]],
	OF_DARKLIGHT = [[0x00100000]],
	OF_ENEMYGENERAL = [[0x01000000]],
	OF_ENEMYFORCE = [[0x02000000]],
	OF_MYGENERAL = [[0x04000000]],
	OF_MYFORCE = [[0x08000000]],
	OF_ATTACKENEMY = [[0x03000000]],
	OF_ATTACKMY = [[0x0c000000]],
	OF_ATTACKALL = [[0x0F000000]],
	OF_TARGET = [[0x00200000]],
	OF_BOMB = [[0x00400000]],
	OM_ALLOCATE = [[0x00000001]],
	OM_TICK = [[0x00000002]],
	OM_REMOVE = [[0x00000003]],
	OM_ATTACK = [[0x00010000]],
	OM_WALK = [[0x00010001]],
	OM_WAIT = [[0x00010002]],
	OM_DEATH = [[0x00010003]],
	OM_PAIN = [[0x00010004]],
	OM_TOUCHER = [[0x00010005]],
	OM_TOUCHED = [[0x00010006]],
	OM_INITATTACK = [[0x00010007]],
	OM_INITDEATH = [[0x00010008]],
	OM_DEATHSTOP = [[0x00010009]],
	OM_FLEERUN = [[0x0001000C]],
	OM_SETTARGET = [[0x00020001]],
}

Troop = {
	{ Name = [[师团移动时的物件]], Sequence = [[51]], Type = [[2]], FLAGS = [[OF_MAN+OF_TRIGGERMAN]], Process = [[%TroopObjectProcess]], Directory = [[\Troop\]],  },
	{ Name = [[师团移动时的物件(1)]], Sequence = [[52]], Type = [[2]], FLAGS = [[0]], Process = [[%TroopShapeObjectProcess]], Directory = [[\Troop\]],  },
	{ Name = [[师团移动时的物件(2)]], Sequence = [[53]], Type = [[2]], FLAGS = [[0]], Process = [[%TroopShapeObjectProcess]], Directory = [[\Troop\]],  },
	{ Name = [[师团移动时的物件(3)]], Sequence = [[54]], Type = [[2]], FLAGS = [[0]], Process = [[%TroopShapeObjectProcess]], Directory = [[\Troop\]],  },
}

Flags = {
	{ Name = [[Troop Flags 1]], Sequence = [[1]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 2]], Sequence = [[2]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 3]], Sequence = [[3]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 4]], Sequence = [[4]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 5]], Sequence = [[5]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 6]], Sequence = [[6]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 7]], Sequence = [[7]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 8]], Sequence = [[8]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 9]], Sequence = [[9]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 10]], Sequence = [[10]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 11]], Sequence = [[11]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 12]], Sequence = [[12]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 13]], Sequence = [[13]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 14]], Sequence = [[14]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 15]], Sequence = [[15]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 16]], Sequence = [[16]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 17]], Sequence = [[17]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 18]], Sequence = [[18]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 19]], Sequence = [[19]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 20]], Sequence = [[20]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 21]], Sequence = [[21]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 22]], Sequence = [[22]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 23]], Sequence = [[23]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 24]], Sequence = [[24]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 25]], Sequence = [[25]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 26]], Sequence = [[26]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
	{ Name = [[Troop Flags 27]], Sequence = [[27]], Type = [[%TYPE_BASE]], FLAGS = [[0]], Process = [[%TroopFlagsProcess]], Directory = [[\Troop\]],  },
}

Soldier = {
	{ Name = [[朴刀兵]], Sequence = [[100]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[长枪兵]], Sequence = [[101]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[大刀兵]], Sequence = [[102]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弓箭兵]], Sequence = [[103]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[链锤兵]], Sequence = [[104]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[飞刀兵]], Sequence = [[105]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[武斗兵]], Sequence = [[106]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[蛮族兵]], Sequence = [[107]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[铁鎚兵]], Sequence = [[108]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[藤甲兵]], Sequence = [[109]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[黄巾贼]], Sequence = [[110]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弩兵]], Sequence = [[111]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[女兵]], Sequence = [[112]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[朴刀兵(红军)]], Sequence = [[120]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[长枪兵(红军)]], Sequence = [[121]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[大刀兵(红军)]], Sequence = [[122]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弓箭兵(红军)]], Sequence = [[123]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[链锤兵(红军)]], Sequence = [[124]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[飞刀兵(红军)]], Sequence = [[125]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[武斗兵(红军)]], Sequence = [[126]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[蛮族兵(红军)]], Sequence = [[127]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[铁鎚兵(红军)]], Sequence = [[128]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[藤甲兵(红军)]], Sequence = [[129]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[黄巾贼(红军)]], Sequence = [[130]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弩兵(红军)]], Sequence = [[131]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[女兵(红军)]], Sequence = [[132]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[朴刀兵 (骑兵)]], Sequence = [[140]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[长枪兵 (骑兵)]], Sequence = [[141]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[大刀兵 (骑兵)]], Sequence = [[142]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弓箭兵 (骑兵)]], Sequence = [[143]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[链锤兵 (骑兵)]], Sequence = [[144]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[飞刀兵 (骑兵)]], Sequence = [[145]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[武斗兵 (骑兵)]], Sequence = [[146]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[蛮族兵 (骑兵)]], Sequence = [[147]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[铁鎚兵 (骑兵)]], Sequence = [[148]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[藤甲兵 (骑兵)]], Sequence = [[149]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[黄巾贼 (骑兵)]], Sequence = [[150]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弩兵 (骑兵)]], Sequence = [[151]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[女兵 (骑兵)]], Sequence = [[152]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[朴刀兵 (骑兵)(红军)]], Sequence = [[160]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[长枪兵 (骑兵)(红军)]], Sequence = [[161]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[大刀兵 (骑兵)(红军)]], Sequence = [[162]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弓箭兵 (骑兵)(红军)]], Sequence = [[163]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[链锤兵 (骑兵)(红军)]], Sequence = [[164]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[飞刀兵 (骑兵)(红军)]], Sequence = [[165]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[武斗兵 (骑兵)(红军)]], Sequence = [[166]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[蛮族兵 (骑兵)(红军)]], Sequence = [[167]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[铁鎚兵 (骑兵)(红军)]], Sequence = [[168]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[藤甲兵 (骑兵)(红军)]], Sequence = [[169]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[黄巾贼 (骑兵)(红军)]], Sequence = [[170]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弩兵 (骑兵)(红军)]], Sequence = [[171]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[女兵 (骑兵)(红军)]], Sequence = [[172]], Type = [[%TYPE_FORCE]], Process = [[%ForceSoldierObjectProcess]], Directory = [[\Force\]],  },
}

DeadHorse = {
	{ Name = [[马(蓝军) 骑兵死亡後的马]], Sequence = [[180]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(蓝军) 骑兵死亡後的马]], Sequence = [[181]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(蓝军) 骑兵死亡後的马]], Sequence = [[182]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(蓝军) 骑兵死亡後的马]], Sequence = [[183]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(蓝军) 骑兵死亡後的马]], Sequence = [[184]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(蓝军) 骑兵死亡後的马]], Sequence = [[185]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(红军) 骑兵死亡後的马]], Sequence = [[190]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(红军) 骑兵死亡後的马]], Sequence = [[191]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(红军) 骑兵死亡後的马]], Sequence = [[192]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(红军) 骑兵死亡後的马]], Sequence = [[193]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(红军) 骑兵死亡後的马]], Sequence = [[194]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
	{ Name = [[马(红军) 骑兵死亡後的马]], Sequence = [[195]], Type = [[%TYPE_FORCE]], Life = [[1200]], Process = [[%ForceHorseProcess]], Directory = [[\Force\]],  },
}

ThrownWeapon = {
	{ Name = [[弓箭	(射出去的弓箭)]], Sequence = [[500]], Type = [[%TYPE_FORCE]], Life = [[2400]], Process = [[%ForceArrowObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[飞刀	(射出去的飞刀)]], Sequence = [[501]], Type = [[%TYPE_FORCE]], Life = [[2400]], Process = [[%ForceArrowObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[链锤	(射出去的链锤)]], Sequence = [[502]], Type = [[%TYPE_FORCE]], Life = [[2400]], Process = [[%ForceArrowObjectProcess]], Directory = [[\Force\]],  },
	{ Name = [[弩箭	(弩兵射出去的箭)]], Sequence = [[503]], Type = [[%TYPE_FORCE]], Life = [[2400]], Process = [[%ForceArrowObjectProcess]], Directory = [[\Force\]],  },
}

General = {
	{ Name = [[主将L1 (主体) - 剑]], Sequence = [[600]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L1 (主体) - 枪]], Sequence = [[601]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L1 (主体) - 矛]], Sequence = [[602]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L1 (主体) - 刀]], Sequence = [[603]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L2 (主体) - 剑]], Sequence = [[604]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L2 (主体) - 枪]], Sequence = [[605]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L2 (主体) - 矛]], Sequence = [[606]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L2 (主体) - 刀]], Sequence = [[607]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L3 (主体) - 剑]], Sequence = [[608]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L3 (主体) - 枪]], Sequence = [[609]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L3 (主体) - 矛]], Sequence = [[610]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L3 (主体) - 刀]], Sequence = [[611]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L4 (主体) - 剑]], Sequence = [[612]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L4 (主体) - 枪]], Sequence = [[613]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L4 (主体) - 矛]], Sequence = [[614]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L4 (主体) - 刀]], Sequence = [[615]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L5 (主体) - 剑]], Sequence = [[616]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L5 (主体) - 枪]], Sequence = [[617]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L5 (主体) - 矛]], Sequence = [[618]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L5 (主体) - 刀]], Sequence = [[619]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L6 (主体) - 剑]], Sequence = [[620]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L6 (主体) - 枪]], Sequence = [[621]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L6 (主体) - 矛]], Sequence = [[622]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L6 (主体) - 刀]], Sequence = [[623]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L7 (主体) - 剑]], Sequence = [[624]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L7 (主体) - 枪]], Sequence = [[625]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L7 (主体) - 矛]], Sequence = [[626]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L7 (主体) - 刀]], Sequence = [[627]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L8 (主体) - 剑]], Sequence = [[628]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L8 (主体) - 枪]], Sequence = [[629]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L8 (主体) - 矛]], Sequence = [[630]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L8 (主体) - 刀]], Sequence = [[631]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L9 (主体) - 剑]], Sequence = [[632]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L9 (主体) - 枪]], Sequence = [[633]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L9 (主体) - 矛]], Sequence = [[634]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L9 (主体) - 刀]], Sequence = [[635]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LA (主体) - 剑]], Sequence = [[636]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LA (主体) - 枪]], Sequence = [[637]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LA (主体) - 矛]], Sequence = [[638]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LA (主体) - 刀]], Sequence = [[639]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LB (主体) - 剑]], Sequence = [[640]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LB (主体) - 枪]], Sequence = [[641]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LB (主体) - 矛]], Sequence = [[642]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LB (主体) - 刀]], Sequence = [[643]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LC (主体) - 剑]], Sequence = [[644]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LC (主体) - 枪]], Sequence = [[645]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LC (主体) - 矛]], Sequence = [[646]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LC (主体) - 刀]], Sequence = [[647]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LD (主体) - 剑]], Sequence = [[648]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LD (主体) - 枪]], Sequence = [[649]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LD (主体) - 矛]], Sequence = [[650]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LD (主体) - 刀]], Sequence = [[651]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LE (主体) - 剑]], Sequence = [[652]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LE (主体) - 枪]], Sequence = [[653]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LE (主体) - 矛]], Sequence = [[654]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将LE (主体) - 刀]], Sequence = [[655]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 剑]], Sequence = [[656]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 枪]], Sequence = [[657]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 矛]], Sequence = [[658]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 刀]], Sequence = [[659]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R1 (红军)(主体) - 剑]], Sequence = [[800]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R1 (红军)(主体) - 枪]], Sequence = [[801]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R1 (红军)(主体) - 矛]], Sequence = [[802]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R1 (红军)(主体) - 刀]], Sequence = [[803]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R2 (红军)(主体) - 剑]], Sequence = [[804]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R2 (红军)(主体) - 枪]], Sequence = [[805]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R2 (红军)(主体) - 矛]], Sequence = [[806]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R2 (红军)(主体) - 刀]], Sequence = [[807]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R3 (红军)(主体) - 剑]], Sequence = [[808]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R3 (红军)(主体) - 枪]], Sequence = [[809]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R3 (红军)(主体) - 矛]], Sequence = [[810]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R3 (红军)(主体) - 刀]], Sequence = [[811]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R4 (红军)(主体) - 剑]], Sequence = [[812]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R4 (红军)(主体) - 枪]], Sequence = [[813]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R4 (红军)(主体) - 矛]], Sequence = [[814]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R4 (红军)(主体) - 刀]], Sequence = [[815]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R5 (红军)(主体) - 剑]], Sequence = [[816]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R5 (红军)(主体) - 枪]], Sequence = [[817]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R5 (红军)(主体) - 矛]], Sequence = [[818]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R5 (红军)(主体) - 刀]], Sequence = [[819]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R6 (红军)(主体) - 剑]], Sequence = [[820]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R6 (红军)(主体) - 枪]], Sequence = [[821]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R6 (红军)(主体) - 矛]], Sequence = [[822]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R6 (红军)(主体) - 刀]], Sequence = [[823]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R7 (红军)(主体) - 剑]], Sequence = [[824]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R7 (红军)(主体) - 枪]], Sequence = [[825]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R7 (红军)(主体) - 矛]], Sequence = [[826]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R7 (红军)(主体) - 刀]], Sequence = [[827]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R8 (红军)(主体) - 剑]], Sequence = [[828]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R8 (红军)(主体) - 枪]], Sequence = [[829]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R8 (红军)(主体) - 矛]], Sequence = [[830]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R8 (红军)(主体) - 刀]], Sequence = [[831]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R9 (红军)(主体) - 剑]], Sequence = [[832]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R9 (红军)(主体) - 枪]], Sequence = [[833]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R9 (红军)(主体) - 矛]], Sequence = [[834]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R9 (红军)(主体) - 刀]], Sequence = [[835]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RA (红军)(主体) - 剑]], Sequence = [[836]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RA (红军)(主体) - 枪]], Sequence = [[837]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RA (红军)(主体) - 矛]], Sequence = [[838]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RA (红军)(主体) - 刀]], Sequence = [[839]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RB (红军)(主体) - 剑]], Sequence = [[840]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RB (红军)(主体) - 枪]], Sequence = [[841]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RB (红军)(主体) - 矛]], Sequence = [[842]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RB (红军)(主体) - 刀]], Sequence = [[843]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RC (红军)(主体) - 剑]], Sequence = [[844]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RC (红军)(主体) - 枪]], Sequence = [[845]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RC (红军)(主体) - 矛]], Sequence = [[846]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RC (红军)(主体) - 刀]], Sequence = [[847]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RD (红军)(主体) - 剑]], Sequence = [[848]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RD (红军)(主体) - 枪]], Sequence = [[849]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RD (红军)(主体) - 矛]], Sequence = [[850]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RD (红军)(主体) - 刀]], Sequence = [[851]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RE (红军)(主体) - 剑]], Sequence = [[852]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RE (红军)(主体) - 枪]], Sequence = [[853]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RE (红军)(主体) - 矛]], Sequence = [[854]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将RE (红军)(主体) - 刀]], Sequence = [[855]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将R0 (主体) - 剑]], Sequence = [[856]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 枪]], Sequence = [[857]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 矛]], Sequence = [[858]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
	{ Name = [[主将L0 (主体) - 刀]], Sequence = [[859]], Type = [[%TYPE_MAJOR]], Process = [[%ForceMajorObjectProcess]], Directory = [[\MAJOR\BODY]],  },
}

Weapon = {
	{ Name = [[主将 (武器)直剑]], Sequence = [[700]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)吴钩剑]], Sequence = [[701]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)青铜剑]], Sequence = [[702]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)流星鎚]], Sequence = [[703]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)弧月刀]], Sequence = [[704]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)双股剑]], Sequence = [[705]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)龙渊剑]], Sequence = [[706]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)青釭剑]], Sequence = [[707]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)古锭刀]], Sequence = [[708]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)七星剑]], Sequence = [[709]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)倚天剑]], Sequence = [[710]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)圆锥枪]], Sequence = [[720]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)钩鎌枪]], Sequence = [[721]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)马叉]], Sequence = [[722]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)金杀]], Sequence = [[723]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)月牙戟]], Sequence = [[724]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)双铁戟]], Sequence = [[725]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)紫龙戟]], Sequence = [[726]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)方天画戟]], Sequence = [[727]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)铜殳]], Sequence = [[740]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)蛇矛]], Sequence = [[741]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)铜长刀]], Sequence = [[742]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)铁钺戟]], Sequence = [[743]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)三尖刀]], Sequence = [[744]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)铁脊蛇矛]], Sequence = [[745]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)丈八蛇矛]], Sequence = [[746]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)眉尖刀]], Sequence = [[760]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)凤嘴刀]], Sequence = [[761]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)大斧]], Sequence = [[762]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)狼牙棒]], Sequence = [[763]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)两刃斧]], Sequence = [[764]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)铁蒺藜骨朵]], Sequence = [[765]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)青龙刀]], Sequence = [[766]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
	{ Name = [[主将 (武器)青龙偃月刀]], Sequence = [[767]], Type = [[%TYPE_MAJOR]], Process = [[%MajorGeneralWeaponProcess]], Directory = [[\MAJOR\WEAPON]],  },
}

Horse = {
	{ Name = [[主将1 (马)]], Sequence = [[900]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将2 (马)]], Sequence = [[901]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将3 (马)]], Sequence = [[902]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将4 (马)]], Sequence = [[903]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将5 (马)]], Sequence = [[904]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将6 (马)]], Sequence = [[905]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将7 (马)]], Sequence = [[906]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
	{ Name = [[主将8 (马)]], Sequence = [[907]], Type = [[%TYPE_MAJOR]], Process = [[%MajorHorseProcess]], Directory = [[\MAJOR\HORSE]],  },
}

Scene = {
	{ Name = [[树]], Sequence = [[400]], Type = [[%TYPE_BASE]], Flags = [[OF_BACKGROUND]], Process = [[%DefaultObjectProcess]], Directory = [[\BG]],  },
	{ Name = [[树]], Sequence = [[401]], Type = [[%TYPE_BASE]], Flags = [[OF_BACKGROUND]], Process = [[%DefaultObjectProcess]], Directory = [[\BG]],  },
	{ Name = [[石头]], Sequence = [[402]], Type = [[%TYPE_BASE]], Flags = [[OF_BACKGROUND]], Process = [[%DefaultObjectProcess]], Directory = [[\BG]],  },
	{ Name = [[火台]], Sequence = [[403]], Type = [[%TYPE_BASE]], Flags = [[OF_BACKGROUND]], Process = [[%DefaultObjectProcess]], Directory = [[\BG]],  },
	{ Name = [[火]], Sequence = [[404]], Type = [[%TYPE_BASE]], Process = [[%DefaultObjectProcess]], Directory = [[\BG]],  },
	{ Name = [[虚幻物件 (没有任何图形)]], Sequence = [[1011]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\]],  },
	{ Name = [[影子 (没有固定图形)]], Sequence = [[1012]], Type = [[%TYPE_FORCE]], Process = [[%ShadowObjectProcess]], Directory = [[\]],  },
	{ Name = [[虚幻物件 (没有任何图形)]], Sequence = [[1013]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%AniObjectProcess]], Directory = [[\]],  },
	{ Name = [[雨水]], Sequence = [[9994]], Type = [[%TYPE_FORCE]], Process = [[OF_BOMB]], Directory = [[%WeatherObjectProcess]], Wait = [[\]],  },
	{ Name = [[雨水]], Sequence = [[9995]], Type = [[%TYPE_FORCE]], Process = [[OF_BOMB]], Directory = [[%WeatherObjectProcess]], Wait = [[\]],  },
	{ Name = [[雨水]], Sequence = [[9996]], Type = [[%TYPE_FORCE]], Process = [[OF_BOMB]], Directory = [[%WeatherObjectProcess]], Wait = [[\]],  },
	{ Name = [[无形有重力]], Sequence = [[2500]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\000]],  },
	{ Name = [[无形无重力]], Sequence = [[2501]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\000]],  },
}

Magic = {
	{ Name = [[火球]], Sequence = [[10003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气A]], Sequence = [[10004]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气B]], Sequence = [[10005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气C]], Sequence = [[10006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气D]], Sequence = [[10007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气E]], Sequence = [[10008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气F]], Sequence = [[10009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气G]], Sequence = [[10010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[集气H]], Sequence = [[10011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[血]], Sequence = [[10012]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[紫球]], Sequence = [[10013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[青球]], Sequence = [[10014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[士兵着火]], Sequence = [[10015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[士兵着火]], Sequence = [[10016]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\000]],  },
	{ Name = [[掉下的不动锅]], Sequence = [[10017]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\000]],  },
	{ Name = [[掉下的不动锅]], Sequence = [[10018]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\000]],  },
	{ Name = [[半月斩]], Sequence = [[11001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\001]],  },
	{ Name = [[半月斩爆炸]], Sequence = [[11002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\001]],  },
	{ Name = [[烟尘A]], Sequence = [[11003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\001]],  },
	{ Name = [[飞行武器箭（M012）]], Sequence = [[13001]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器箭的光（M012）]], Sequence = [[13002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器小刀（M012）]], Sequence = [[13003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器小刀的光（M012）]], Sequence = [[13004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器戟（M012）]], Sequence = [[13005]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器戟的光（M012）]], Sequence = [[13006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器箭的光（M012）]], Sequence = [[13007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器BOMB的光（M012）]], Sequence = [[13008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[飞行武器BOMB的光（M012）]], Sequence = [[13009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[落日弓的尾巴光]], Sequence = [[13010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[落月弓的头光]], Sequence = [[13011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\003]],  },
	{ Name = [[冲车]], Sequence = [[14001]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\004]],  },
	{ Name = [[闪电A]], Sequence = [[15001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[闪电B]], Sequence = [[15002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[闪电C]], Sequence = [[15003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[烟]], Sequence = [[15004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[波及闪电]], Sequence = [[15005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[波及闪电]], Sequence = [[15006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[士兵身上的电]], Sequence = [[15007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[大型闪电（M009）]], Sequence = [[15008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[大型闪电（M009）]], Sequence = [[15009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[闪电]], Sequence = [[15010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\005]],  },
	{ Name = [[向上射弓箭的蓝小兵]], Sequence = [[16001]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[向上射弓箭的红小兵]], Sequence = [[16002]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[向上飞的箭]], Sequence = [[16003]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[我方向下飞的箭]], Sequence = [[16004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[静止的蓝小兵]], Sequence = [[16005]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[静止的红小兵]], Sequence = [[16006]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[敌方向下飞的箭]], Sequence = [[16007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[停止的箭火]], Sequence = [[16008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[向上飞的箭火]], Sequence = [[16009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[向下飞的箭火]], Sequence = [[16010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[着火士兵身上的火]], Sequence = [[16011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\006]],  },
	{ Name = [[断箭A]], Sequence = [[16012]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[断箭B]], Sequence = [[16013]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[断箭C]], Sequence = [[16014]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[断箭D]], Sequence = [[16015]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[断箭E]], Sequence = [[16016]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[断箭F]], Sequence = [[16017]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[断箭G]], Sequence = [[16018]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\006]],  },
	{ Name = [[着火士兵身上的火]], Sequence = [[17001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[投石车]], Sequence = [[17002]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[投石]], Sequence = [[17003]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[投石影子]], Sequence = [[17004]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[我方向下飞的石头]], Sequence = [[17005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[敌方向下飞的石头]], Sequence = [[17006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头碎片]], Sequence = [[17007]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头碎片]], Sequence = [[17008]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头碎片]], Sequence = [[17009]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头碎片]], Sequence = [[17010]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头碎片]], Sequence = [[17011]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[火石爆炸]], Sequence = [[17012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头上的火]], Sequence = [[17013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[我方向下飞的石头]], Sequence = [[17014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[敌方向下飞的石头]], Sequence = [[17015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[火花]], Sequence = [[17016]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[火花]], Sequence = [[17017]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[火花]], Sequence = [[17018]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[火花]], Sequence = [[17019]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[火花]], Sequence = [[17020]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头上的火]], Sequence = [[17021]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[石头上的火]], Sequence = [[17021]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[往上石头上的火]], Sequence = [[17022]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[投石车]], Sequence = [[17023]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\007]],  },
	{ Name = [[着火士兵身上的火]], Sequence = [[18001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\008]],  },
	{ Name = [[扩张的光气环]], Sequence = [[18002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\008]],  },
	{ Name = [[我方的攻击魔法爆炸火]], Sequence = [[18003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\008]],  },
	{ Name = [[我方的攻击魔法爆炸]], Sequence = [[18004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\008]],  },
	{ Name = [[着火士兵身上的火]], Sequence = [[19001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\009]],  },
	{ Name = [[我方的攻击魔法火]], Sequence = [[19002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\009]],  },
	{ Name = [[地剑]], Sequence = [[20001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[地剑]], Sequence = [[20010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\010]],  },
	{ Name = [[碎石A]], Sequence = [[20011]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\010]],  },
	{ Name = [[碎石B]], Sequence = [[20012]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\010]],  },
	{ Name = [[碎石C]], Sequence = [[20013]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\010]],  },
	{ Name = [[碎石D]], Sequence = [[20014]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\010]],  },
	{ Name = [[龙卷风]], Sequence = [[21001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\011]],  },
	{ Name = [[龙卷风]], Sequence = [[21002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\011]],  },
	{ Name = [[石粒]], Sequence = [[21003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\011]],  },
	{ Name = [[剑气地上尾光]], Sequence = [[22001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\012]],  },
	{ Name = [[分身冲刺]], Sequence = [[22002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\012]],  },
	{ Name = [[定身]], Sequence = [[23001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[定身]], Sequence = [[23016]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\013]],  },
	{ Name = [[WAVE]], Sequence = [[24001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\014]],  },
	{ Name = [[WAVE]], Sequence = [[24002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\014]],  },
	{ Name = [[WAVE]], Sequence = [[24003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\014]],  },
	{ Name = [[WAVE]], Sequence = [[24004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\014]],  },
	{ Name = [[WAVE]], Sequence = [[24005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\014]],  },
	{ Name = [[外围的电珠]], Sequence = [[25001]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\015]],  },
	{ Name = [[外围的电珠]], Sequence = [[25002]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\015]],  },
	{ Name = [[光舞剑]], Sequence = [[25003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\015]],  },
	{ Name = [[光舞剑]], Sequence = [[25004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\015]],  },
	{ Name = [[光舞剑]], Sequence = [[25005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\015]],  },
	{ Name = [[光舞剑]], Sequence = [[25006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\015]],  },
	{ Name = [[中间的电泡]], Sequence = [[25007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\015]],  },
	{ Name = [[中间的电泡]], Sequence = [[25008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\015]],  },
	{ Name = [[外围的电珠]], Sequence = [[25009]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\015]],  },
	{ Name = [[外围的电珠]], Sequence = [[25010]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\015]],  },
	{ Name = [[圣光A]], Sequence = [[26001]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\016]],  },
	{ Name = [[圣光B]], Sequence = [[26002]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\016]],  },
	{ Name = [[圣光C]], Sequence = [[26003]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\016]],  },
	{ Name = [[圣光D]], Sequence = [[26004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\016]],  },
	{ Name = [[圣光E]], Sequence = [[26005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\016]],  },
	{ Name = [[圣光F]], Sequence = [[26006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\016]],  },
	{ Name = [[着火士兵身上的火（M002）]], Sequence = [[27001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，头（M015）]], Sequence = [[27002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，头（M015）]], Sequence = [[27003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，头（M015）]], Sequence = [[27004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，身（M015）]], Sequence = [[27005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，身（M015）]], Sequence = [[27006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，尾（M015）]], Sequence = [[27007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，尾（M015）]], Sequence = [[27008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[火龙，尾（M015）]], Sequence = [[27009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[起点]], Sequence = [[27010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\017]],  },
	{ Name = [[龙	(召唤兽)]], Sequence = [[28001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[火]], Sequence = [[28002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[火]], Sequence = [[28003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[火]], Sequence = [[28004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[火柱]], Sequence = [[28005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[中间的电泡（M009）]], Sequence = [[28006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[中间的电泡（M009）]], Sequence = [[28007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[外围的电珠（M009）]], Sequence = [[28008]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[外围的电珠（M009）]], Sequence = [[28009]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[着火士兵身上的火（M002）]], Sequence = [[28010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\018]],  },
	{ Name = [[我方的攻击魔法爆炸火（M005）]], Sequence = [[28011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\018]],  },
	{ Name = [[火柱]], Sequence = [[28012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\MAGIC\018]],  },
	{ Name = [[飞行武器箭]], Sequence = [[29001]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\019]],  },
	{ Name = [[飞行武器箭的光]], Sequence = [[29002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\019]],  },
	{ Name = [[黑洞]], Sequence = [[30001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[黑洞]], Sequence = [[30002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星A]], Sequence = [[30003]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星B]], Sequence = [[30004]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星C]], Sequence = [[30005]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星D]], Sequence = [[30006]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星E]], Sequence = [[30007]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星F]], Sequence = [[30008]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星G]], Sequence = [[30009]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星H]], Sequence = [[30010]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[星星I]], Sequence = [[30011]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[黑洞]], Sequence = [[30012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[黑洞]], Sequence = [[30013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[黑洞]], Sequence = [[30014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[黑洞]], Sequence = [[30015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\020]],  },
	{ Name = [[火焰A]], Sequence = [[31001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\021]],  },
	{ Name = [[石头A]], Sequence = [[31002]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\021]],  },
	{ Name = [[冰雾]], Sequence = [[32001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\022]],  },
	{ Name = [[冰A]], Sequence = [[32002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\022]],  },
	{ Name = [[碎冰A]], Sequence = [[32003]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\magic\022]],  },
	{ Name = [[碎冰B]], Sequence = [[32004]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\magic\022]],  },
	{ Name = [[碎冰C]], Sequence = [[32005]], Type = [[%TYPE_FORCE]], Flags = [[OF_WHITELIGHT]], Process = [[%MagicObjectProcess]], Directory = [[\magic\022]],  },
	{ Name = [[火A]], Sequence = [[33001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\023]],  },
	{ Name = [[烟]], Sequence = [[33002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\023]],  },
	{ Name = [[太极A]], Sequence = [[35001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\025]],  },
	{ Name = [[太极B]], Sequence = [[35002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\025]],  },
	{ Name = [[水柱]], Sequence = [[36001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[石头A]], Sequence = [[36002]], Type = [[%TYPE_FORCE]], Flags = [[OF_NONSYNCHRONISM]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[石头B]], Sequence = [[36003]], Type = [[%TYPE_FORCE]], Flags = [[OF_NONSYNCHRONISM]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱A]], Sequence = [[36004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱B]], Sequence = [[36005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱C]], Sequence = [[36006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱D]], Sequence = [[36007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱E]], Sequence = [[36008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱F]], Sequence = [[36009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱G]], Sequence = [[36010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水柱H]], Sequence = [[36011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水泡A]], Sequence = [[36012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[水泡B]], Sequence = [[36013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\026]],  },
	{ Name = [[牛]], Sequence = [[37001]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\027]],  },
	{ Name = [[火焰A]], Sequence = [[37002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\027]],  },
	{ Name = [[石头]], Sequence = [[38001]], Type = [[%TYPE_FORCE]], Flags = [[OF_NONSYNCHRONISM]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片A]], Sequence = [[38002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片B]], Sequence = [[38003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片C]], Sequence = [[38004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片D]], Sequence = [[38005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片E]], Sequence = [[38006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片F]], Sequence = [[38007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[石头碎片G]], Sequence = [[38008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\028]],  },
	{ Name = [[八卦]], Sequence = [[39001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39016]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39017]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39018]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39019]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39020]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39021]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39022]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39023]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39024]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39025]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39026]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39027]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39028]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39029]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[八卦]], Sequence = [[39030]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\029]],  },
	{ Name = [[半月斩]], Sequence = [[40001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\030]],  },
	{ Name = [[半月斩]], Sequence = [[40002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\030]],  },
	{ Name = [[爆炸的光]], Sequence = [[40003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\030]],  },
	{ Name = [[火球]], Sequence = [[41001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火柱A]], Sequence = [[41002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火柱B]], Sequence = [[41003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火柱C]], Sequence = [[41004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火柱D]], Sequence = [[41005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火]], Sequence = [[41008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火]], Sequence = [[41009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[火]], Sequence = [[41010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\031]],  },
	{ Name = [[电球]], Sequence = [[42001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\032]],  },
	{ Name = [[电球]], Sequence = [[42002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\032]],  },
	{ Name = [[电球]], Sequence = [[42003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\032]],  },
	{ Name = [[电球]], Sequence = [[42004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\032]],  },
	{ Name = [[蓝炮]], Sequence = [[43001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\033]],  },
	{ Name = [[炮弹]], Sequence = [[43002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\033]],  },
	{ Name = [[爆炸]], Sequence = [[43003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\033]],  },
	{ Name = [[烟火]], Sequence = [[43004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\033]],  },
	{ Name = [[红炮]], Sequence = [[43005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\033]],  },
	{ Name = [[炮弹]], Sequence = [[43006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\033]],  },
	{ Name = [[桶子]], Sequence = [[44001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[烟]], Sequence = [[44002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[爆炸]], Sequence = [[44003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[烟]], Sequence = [[44004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片A]], Sequence = [[44005]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片B]], Sequence = [[44006]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片C]], Sequence = [[44007]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片D]], Sequence = [[44008]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片E]], Sequence = [[44009]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片F]], Sequence = [[44010]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[桶子碎片G]], Sequence = [[44011]], Type = [[%TYPE_FORCE]], Flags = [[OF_BIGSHAPE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\034]],  },
	{ Name = [[矛]], Sequence = [[45001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\035]],  },
	{ Name = [[矛]], Sequence = [[45002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\035]],  },
	{ Name = [[剑1]], Sequence = [[46001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑2]], Sequence = [[46002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑3]], Sequence = [[46003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑4]], Sequence = [[46004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑5]], Sequence = [[46005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑6]], Sequence = [[46006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑7]], Sequence = [[46007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑8]], Sequence = [[46008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑9]], Sequence = [[46009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑10]], Sequence = [[46010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑11]], Sequence = [[46011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑12]], Sequence = [[46012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑13]], Sequence = [[46013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑14]], Sequence = [[46014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑15]], Sequence = [[46015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[剑16]], Sequence = [[46016]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\036]],  },
	{ Name = [[火柱A]], Sequence = [[47001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\037]],  },
	{ Name = [[火柱B]], Sequence = [[47002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\037]],  },
	{ Name = [[火柱C]], Sequence = [[47003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\037]],  },
	{ Name = [[火柱D]], Sequence = [[47004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\037]],  },
	{ Name = [[剑A1]], Sequence = [[48001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A2]], Sequence = [[48002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A3]], Sequence = [[48003]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A4]], Sequence = [[48004]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A5]], Sequence = [[48005]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A6]], Sequence = [[48006]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A7]], Sequence = [[48007]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A8]], Sequence = [[48008]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A9]], Sequence = [[48009]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A10]], Sequence = [[48010]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A11]], Sequence = [[48011]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A12]], Sequence = [[48012]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A13]], Sequence = [[48013]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A14]], Sequence = [[48014]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A15]], Sequence = [[48015]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑A16]], Sequence = [[48016]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B1]], Sequence = [[48017]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B2]], Sequence = [[48018]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B3]], Sequence = [[48019]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B4]], Sequence = [[48020]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B5]], Sequence = [[48021]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B6]], Sequence = [[48022]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B7]], Sequence = [[48023]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B8]], Sequence = [[48024]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B9]], Sequence = [[48025]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B10]], Sequence = [[48026]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B11]], Sequence = [[48027]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B12]], Sequence = [[48028]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B13]], Sequence = [[48029]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B14]], Sequence = [[48030]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B15]], Sequence = [[48031]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[剑B16]], Sequence = [[48032]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\038]],  },
	{ Name = [[桶子]], Sequence = [[49001]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片A]], Sequence = [[49002]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片B]], Sequence = [[49003]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片C]], Sequence = [[49004]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片D]], Sequence = [[49005]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片E]], Sequence = [[49006]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片F]], Sequence = [[49007]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[桶子碎片G]], Sequence = [[49008]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\039]],  },
	{ Name = [[石柱]], Sequence = [[50001]], Type = [[%TYPE_FORCE]], Flags = [[OF_NOGRAVITY]], Process = [[%MagicObjectProcess]], Directory = [[\magic\040]],  },
	{ Name = [[烟]], Sequence = [[50002]], Type = [[%TYPE_FORCE]], Process = [[%MagicObjectProcess]], Directory = [[\magic\040]],  },
	{ Name = [[拒马]], Sequence = [[51001]], Type = [[%TYPE_FORCE]], Flags = [[0]], Process = [[%MagicObjectProcess]], Directory = [[\magic\041]],  },
}
